package com.karimandco.pdf;

import com.itextpdf.text.BadElementException;
import com.karimandco.auth.Utilisateur;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Tom, Léo, Lorenzo
 */
public class VoirPdf extends javax.swing.JPanel {

    private String nom = "";
    private String prenom = "";
    private String numero = "";
    private String lienPDF = "";
    private Pdf pdf = null;
    private Collection<Pdf> lesPdf;

    /**
     * Creates new form VoirPdf
     */
    public VoirPdf() {
        initComponents();
        lesPdf = new Collection<Pdf>();
        nom = "exemple";
        prenom = "exemple";
        numero = "exemple";
        lienPDF = "exemple";
        jLabelChargement.setText("");
        this.pdf = new Pdf(Utilisateur.getInstance().getNom(), Utilisateur.getInstance().getPrenom(), Utilisateur.getInstance().getNumeroTelephone(), lienPDF);
//        jLabelChargement.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appercu = new javax.swing.JButton();
        jLabelChargement = new javax.swing.JLabel();

        appercu.setText("Voir le pdf");
        appercu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appercuActionPerformed(evt);
            }
        });

        jLabelChargement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChargement.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(appercu, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                    .addComponent(jLabelChargement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(appercu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelChargement, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String adjouterAuFichierASupprimer() {
        String fichierADelete = this.pdf.getUrlCv();
        return fichierADelete;
    }

    public String ajouterUnCv() {
        String tableau = adjouterAuFichierASupprimer() + "|" + this.pdf.getUrlCv();
        return tableau;
    }


    private void appercuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appercuActionPerformed

        this.pdf = new Pdf(nom, prenom, numero, lienPDF);

        System.out.println(ajouterUnCv());
        if (pdf.verifPDF()) {
            try {
                pdf.genererPDF();
                LecteurPDF lecteur = new LecteurPDF(pdf.getUrlCv());
                //créer le JFrame
                JFrame f = new JFrame("Lecteur PDF");
                f.setSize(1024, 768);
                f.setLocationRelativeTo(this);
                f.getContentPane().add(lecteur);
                f.setVisible(true);
                f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

                System.out.println(pdf.getUrlCv());

                lesPdf.ajouterElement(this.pdf);
                for (int i = 0; i < lesPdf.nbElement(); i++) {
                    this.lesPdf.conversionEnTableau();
                }

                File monfichier = new File(pdf.getUrlCv());
                System.out.println(lesPdf.nbElement());
                monfichier.deleteOnExit();

            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "Erreur", "PDF", JOptionPane.ERROR_MESSAGE);
                jLabelChargement.setText("Erreur lors du chargement de votre cv.");
                jLabelChargement.setForeground(Color.red);
            } catch (BadElementException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
                jLabelChargement.setText("Erreur lors du chargement de votre cv.");
                jLabelChargement.setForeground(Color.red);
            } catch (IOException ex) {
                Logger.getLogger(PanelPDF.class.getName()).log(Level.SEVERE, null, ex);
                jLabelChargement.setText("Erreur lors du chargement de votre cv.");
                jLabelChargement.setForeground(Color.red);
            } catch (Exception ex) {
                Logger.getLogger(VoirPdf.class.getName()).log(Level.SEVERE, null, ex);
                jLabelChargement.setText("Erreur lors du chargement de votre cv.");
                jLabelChargement.setForeground(Color.red);
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Erreur");
        }
        System.out.println(pdf.getNomCv());

    }//GEN-LAST:event_appercuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appercu;
    private javax.swing.JLabel jLabelChargement;
    // End of variables declaration//GEN-END:variables
}
