/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xml;

/**
 *
 * @author Galdr
 */
public class XML1 extends javax.swing.JPanel {

    /**
     * Creates new form XML1
     */
    public XML1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        XML1 = new javax.swing.JButton();

        XML1.setText("Export XML");
        XML1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XML1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XML1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(XML1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void XML1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XML1MouseClicked
        ImportExportXML objEXML = new ImportExportXML("export7novembr.xml");
        objEXML.exportFichier();
        System.out.println(objEXML.importFichier());
    }//GEN-LAST:event_XML1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton XML1;
    // End of variables declaration//GEN-END:variables
}
